[profile.default]
src = 'contracts'
test = 'contracts'
out = 'out'
libs = ['lib']
solc_version = "0.8.12"
# Testing
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'

# See more config options https://github.com/gakonst/foundry/tree/master/config
