[profile.default]
src = 'contracts'
test = 'test/solidity'
out = 'out'
libs = ['lib']
solc_version = "0.8.12"
auto_detect_solc = false
evm_version = "london"
optimizer = false
optimizer_runs = 200
via_ir = false
bytecode_hash = "ipfs"
cbor_metadata = true
use_literal_content = false
allow_internal_expect_revert = false

[profile.default.fuzz]
runs = 512
seed = "0x721"

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = true

[profile.ci.fuzz]
runs = 512
seed = "0x721"

[profile.ci.invariant]
runs = 128
depth = 64
fail_on_revert = true

[profile.scheduled.fuzz]
runs = 10000

[profile.scheduled.invariant]
runs = 2000
depth = 128
fail_on_revert = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
