/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBeneficiary,
  IBeneficiaryInterface,
} from "../../../../../contracts/token/modules/interfaces/IBeneficiary";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
    ],
    name: "beneficiaryOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "address payable",
        name: "beneficiary_",
        type: "address",
      },
    ],
    name: "setBeneficiary",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBeneficiary__factory {
  static readonly abi = _abi;
  static createInterface(): IBeneficiaryInterface {
    return new utils.Interface(_abi) as IBeneficiaryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBeneficiary {
    return new Contract(address, _abi, signerOrProvider) as IBeneficiary;
  }
}
