/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBeneficiary__factory } from "./IBeneficiary__factory";
export { ILease__factory } from "./ILease__factory";
export { IRemittance__factory } from "./IRemittance__factory";
export { ITaxation__factory } from "./ITaxation__factory";
export { IValuation__factory } from "./IValuation__factory";
