/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRemittance,
  IRemittanceInterface,
} from "../../../../../contracts/token/modules/interfaces/IRemittance";

const _abi = [
  {
    inputs: [],
    name: "withdrawOutstandingRemittance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRemittance__factory {
  static readonly abi = _abi;
  static createInterface(): IRemittanceInterface {
    return new utils.Interface(_abi) as IRemittanceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRemittance {
    return new Contract(address, _abi, signerOrProvider) as IRemittance;
  }
}
