/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IValuation,
  IValuationInterface,
} from "../../../../../contracts/token/modules/interfaces/IValuation";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
    ],
    name: "valuationOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IValuation__factory {
  static readonly abi = _abi;
  static createInterface(): IValuationInterface {
    return new utils.Interface(_abi) as IValuationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IValuation {
    return new Contract(address, _abi, signerOrProvider) as IValuation;
  }
}
