/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenManagementSol from "./TokenManagement.sol";
export type { tokenManagementSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Beneficiary } from "./Beneficiary";
export type { ERC721 } from "./ERC721";
export type { Lease } from "./Lease";
export type { Remittance } from "./Remittance";
export type { Taxation } from "./Taxation";
export type { Valuation } from "./Valuation";
