/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Beneficiary } from "./Beneficiary";
export type { Lease } from "./Lease";
export type { Remittance } from "./Remittance";
export type { Taxation } from "./Taxation";
export type { TokenManagement } from "./TokenManagement";
export type { Valuation } from "./Valuation";
