/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface IBeneficiaryInterface extends utils.Interface {
  functions: {
    "beneficiaryOf(uint256)": FunctionFragment;
    "setBeneficiary(uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "beneficiaryOf" | "setBeneficiary"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "beneficiaryOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBeneficiary",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "beneficiaryOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBeneficiary",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IBeneficiary extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBeneficiaryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    beneficiaryOf(
      tokenId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setBeneficiary(
      tokenId_: BigNumberish,
      beneficiary_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  beneficiaryOf(
    tokenId_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setBeneficiary(
    tokenId_: BigNumberish,
    beneficiary_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    beneficiaryOf(
      tokenId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setBeneficiary(
      tokenId_: BigNumberish,
      beneficiary_: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    beneficiaryOf(
      tokenId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBeneficiary(
      tokenId_: BigNumberish,
      beneficiary_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    beneficiaryOf(
      tokenId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBeneficiary(
      tokenId_: BigNumberish,
      beneficiary_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
