/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBeneficiary } from "./IBeneficiary";
export type { ILease } from "./ILease";
export type { IRemittance } from "./IRemittance";
export type { ITaxation } from "./ITaxation";
export type { IValuation } from "./IValuation";
