name: "tests"
on:
  workflow_dispatch:
  push:
    branches:
      - "*" # All branches
jobs:
  coverage:
    name: "coverage"
    runs-on: ubuntu-latest
    needs: []
    # SKIP: Is not compatible w/ Hardhat preprocessing configuration and resultantly will not remap Forge-installed dependencies.
    if: False
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Run solidity-coverage"
        run: "yarn coverage"
  solhint:
    name: "solhint"
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Run solhint"
        run: "yarn solhint"
  tests:
    name: "Hardhat Tests"
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Run tests"
        run: "yarn test:hardhat"
  forge-tests:
    name: "Forge Tests"
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: "Install Foundry"
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: "Run tests"
        run: yarn test:forge
